[project]
name = 'Blockchain-Based-Digital-Identity-Access-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-policy]
path = 'contracts/access-policy.clar'
clarity_version = 2
epoch = 2.5

[contracts.access-policy_]
path = 'contracts/access-policy_.clar'
clarity_version = 2
epoch = 2.5

[contracts.audit-logging]
path = 'contracts/audit-logging.clar'
clarity_version = 2
epoch = 2.5

[contracts.authentication]
path = 'contracts/authentication.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
